### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by mathreat** [Mu-Y/lll-tts#1]

**Comment by Mu-Y** [comment]
hello, can you share your command and error message?

**Comment by mathreat** [comment]
When I ran this command with the newest matplotlib version 3.5.3 ：
`CUDA_VISIBLE_DEVICES=0 python train_joint.py --hyper_parameters joint.json --save_dir exp_joint`
I got the following error message：
```
Traceback (most recent call last):
  File "train_joint.py", line 343, in <module>
    eval_loss = evaluate(epoch, eval_data, model, criterion, eval_loaders)
  File "train_joint.py", line 171, in evaluate
    Logger.evaluation(epoch+1, eval_losses, mcd, src_len, trg_len, src, post_trg, post_pred, post_pred_0, stop_pred_probs, stop_trg, a
lignment_0, cla)
  File "/home/ubuntu/lkk/lll-tts/utils/logging.py", line 111, in evaluation
    Logger._sw.add_figure(f"Predicted/generated", Logger._plot_spectrogram(predicted_spec), eval_step)
  File "/home/ubuntu/lkk/lll-tts/utils/logging.py", line 147, in _plot_spectrogram
    librosa.display.specshow(s, sr=hp.sample_rate, hop_length=hf, x_axis='time', y_axis='mel', cmap='magma')
  File "/home/ubuntu/miniconda3/envs/lkk-lll-tts/lib/python3.8/site-packages/librosa/display.py", line 738, in specshow
    __scale_axes(axes, y_axis, 'y')
  File "/home/ubuntu/miniconda3/envs/lkk-lll-tts/lib/python3.8/site-packages/librosa/display.py", line 845, in __scale_axes
    scaler(mode, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 4117, in set_yscale
    ax.yaxis._set_scale(value, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/matplotlib/axis.py", line 761, in _set_scale
    self._scale = mscale.scale_factory(value, self, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/matplotlib/scale.py", line 597, in scale_factory
    return scale_cls(axis, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'linthreshy'
```
However, after I degrade my matplotlib's version with 2.1.0 to fix this problem, another mistake occurred:
```
Traceback (most recent call last):
  File "train_joint.py", line 342, in <module>
    eval_loss = evaluate(epoch, eval_data, model, criterion, eval_loaders)
  File "train_joint.py", line 171, in evaluate
    Logger.evaluation(epoch+1, eval_losses, mcd, src_len, trg_len, src, post_trg, post_pred, post_pred_0, stop_pred_probs, stop_trg, alignment_0, cla)
  File "/home/ubuntu/lkk/lll-tts/utils/logging.py", line 112, in evaluation
    Logger._sw.add_figure(f"Predicted/generated", Logger._plot_spectrogram(predicted_spec), eval_step)
  File "/home/ubuntu/lkk/lll-tts/utils/logging.py", line 146, in _plot_spectrogram
    fig = plt.figure(figsize=(16, 4))
  File "/home/ubuntu/miniconda3/envs/lkk-lll-tts/lib/python3.8/site-packages/matplotlib/pyplot.py", line 528, in figure
    figManager = new_figure_manager(num, figsize=figsize,
  File "/home/ubuntu/miniconda3/envs/lkk-lll-tts/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 170, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/ubuntu/miniconda3/envs/lkk-lll-tts/lib/python3.8/site-packages/matplotlib/backends/backend_tkagg.py", line 1049, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/home/ubuntu/miniconda3/envs/lkk-lll-tts/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:21.0"
```
I think the error is related with the inproper python packages

**Comment by Mu-Y** [comment]
I tested the following version and no errors are reported:
```
>>> matplotlib.__version__
'3.4.3'
>>> librosa.__version__
'0.7.0'
>>> tensorboard.__version__
'2.0.2'
```
Can you try these versions and see whether the errors are still there?
